#!/usr/bin/env python3
# Copyright (c) 2026, the yah264 authors
# SPDX-License-Identifier: GPL-2.0-or-later
"""Regenerate src/common/symbols10.h, the 10-bit library's symbol namespace.

One command line links BOTH encoder archives (item C3-10bit), so every symbol
either archive defines with external linkage has to be unique across the pair.
A name defined in both is not a link error: the linker resolves it from
whichever archive it scanned first, which is an ordering accident, and the only
symptom is a 10-bit object calling 8-bit code.

The public API takes its suffix in include/yah264.h (YAH264_API); this header is
the INTERNAL side, force-included into every translation unit of the 10-bit
library by meson so a 10-bit object both defines and references `<name>_10`.

The list is the union of the archives' defined symbols minus the public ones.
Feed it archives built WITHOUT the namespace, which is what a plain
`meson setup build && meson setup build10 -Dbit_depth=10` on a tree with the
`-include` line removed produces; in practice the 8-bit archive alone is the
superset, since every 10-bit source file is also an 8-bit one.

usage: scripts/gen_symbols10.py build/libyah264.a [build10/libyah264.a ...]
       (writes src/common/symbols10.h; --stdout prints instead)

scripts/symbol_check.sh is the gate that fails when this file goes stale.
"""

import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, os.pardir, "src", "common", "symbols10.h")

HEADER = '''/*
 * symbols10.h - the 10-bit library's internal symbol namespace.
 *
 * Copyright (c) 2026, the yah264 authors
 * SPDX-License-Identifier: GPL-2.0-or-later
 *
 * GENERATED by scripts/gen_symbols10.py; do not edit by hand.
 *
 * Item C3-10bit. One command line links BOTH encoder libraries, so every
 * symbol either library defines with external linkage has to be unique across
 * the pair: a name defined in both archives resolves to whichever archive the
 * linker scanned first, which is an ordering accident and not a build error.
 * The public API takes its suffix in include/yah264.h (YAH264_API); everything
 * below is the INTERNAL side, force-included into every translation unit of the
 * 10-bit library by meson (`-include`) so a 10-bit object both defines and
 * references `<name>_10`. Nothing here reaches the 8-bit library, the CLI, or
 * an installed header.
 *
 * The list is the union of the two archives' defined symbols minus the public
 * ones, and it is checked rather than trusted: scripts/symbol_check.sh (a leg
 * of `make test`) intersects the two archives and fails on any name they share,
 * so a new non-static symbol that is added here and forgotten fails the gate
 * instead of linking to the wrong depth's code.
 */

#ifndef YAH264_SYMBOLS10_H
#define YAH264_SYMBOLS10_H

#if Y264_BIT_DEPTH == 8
#error "symbols10.h is the high-depth library's namespace; Y264_BIT_DEPTH is 8"
#endif

'''

FOOTER = "\n#endif /* YAH264_SYMBOLS10_H */\n"


def defined(archive):
    """Names with external linkage that this archive DEFINES.

    -g is portable; --defined-only is not, so drop the U lines by hand. Apple's
    nm prefixes an underscore, GNU's does not.
    """
    nm = os.environ.get("NM", "nm")
    out = subprocess.run([nm, "-g", archive], capture_output=True, text=True)
    names = set()
    for line in out.stdout.splitlines():
        f = line.split()
        if len(f) == 3 and f[1] != "U":
            names.add(f[2][1:] if f[2].startswith("_") else f[2])
    return names


def main(argv):
    to_stdout = "--stdout" in argv
    archives = [a for a in argv[1:] if not a.startswith("-")]
    if not archives:
        sys.exit(__doc__)

    names = set()
    for a in archives:
        if not os.path.exists(a):
            sys.exit("gen_symbols10: no such archive: " + a)
        names |= defined(a)

    # The public 25 are suffixed by the header's YAH264_API macro, so they must
    # not be suffixed a second time here. A name already carrying the suffix is
    # an archive that was built WITH the namespace; skip it rather than emit
    # `foo_10 -> foo_10_10`.
    internal = sorted(n for n in names
                      if not n.startswith("yah264_") and not n.endswith("_10"))

    width = max(len(n) for n in internal) + 1
    body = "".join("#define %-*s %s_10\n" % (width, n, n) for n in internal)
    text = HEADER + body + FOOTER

    if to_stdout:
        sys.stdout.write(text)
    else:
        with open(OUT, "w") as f:
            f.write(text)
        sys.stderr.write("gen_symbols10: %d internal symbols -> %s\n"
                         % (len(internal), os.path.normpath(OUT)))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
